### ISSUE TITLE
ArrayIndexOutOfBoundsException for numeric character references that exceed Java's `Integer.MAX_VALUE`.

### ISSUE THREAD

**Issue by b4hand** [unbescape/unbescape#9]
This is related to my earlier reported bug #7, but is actually more extreme.

The following statement results in a
```
HtmlEscape.unescapeHtml("&#914351242010;");
```
stack trace that looks similar to the following:

```
java.lang.ArrayIndexOutOfBoundsException: 476792037
	at org.unbescape.html.HtmlEscapeUtil.unescape(HtmlEscapeUtil.java:683)
	at org.unbescape.html.HtmlEscape.unescapeHtml(HtmlEscape.java:616)
...
```

I've tracked this down to the way that unbescape uses a custom string to integer conversion which doesn't do bounds checking and can cause integer overflow. Specifically, it's the `HtmlEscapeUtil.parseIntFromReference`. This can return a negative number which unbescape then later uses as an indicator for a so called `DOUBLE_CODEPOINT` or a symbolic entity reference that gets translated into two Unicode characters.

**Comment by b4hand** [comment]
I filed this as a separate issue because my earlier patch doesn't actually handle this case either. I included an bounds check that only verified if the codepoint was greater than 0x10FFFF. However, because of the integer overflow in `parseIntFromReference` some very large number can actually turn into negative numbers and result in a different exception.
